name: Publish Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
      - name: Print Java version
        run: java -version
      - name: Ensure gradlew executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Ensure jar exists
        run: |
          if [ ! -f build/libs/*.jar ]; then
            echo "Jar file not found!"
            exit 1
          fi
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          body: |
            Release ${{ github.ref_name }}
            Commit: ${{ github.sha }}
      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
      - name: Publish to Modrinth
        uses: some/modrinth-action@v2
        with:
          version: ${{ steps.version.outputs.version }}
      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_VERSION_PAT }}
          project: nsZf0dsg
          version: ${{ steps.version.outputs.version }}
          loaders: velocity
          game-versions: |-
            26.2
            26.1.x
            1.21.x
            1.20.x
            1.19.x
            1.18.x
            1.17.x
            1.16.x
            1.15.x
            1.14.x
            1.13.x
            1.12.x
          files: |
            build/libs/*.jar
          environment: server_only

#TODO: Add steps to autosign the release and create a new key to do so